### PR TITLE
upgrade packages

### PR DESCRIPTION
**Pull request by ooystein**
Fixes dependabot alert on highlight.js

### CODE REVIEW

**Comment by ooystein** [comment]
This is ready for review now

**Review by Brynjulf — CHANGES_REQUESTED** [review]
can't build because of the way we export `seismic-colormap.json`

```javascript
// this works
import seismicColorMap from './seismic-colormap.json';
export { seismicColorMap };

// current, this does not work
export * as seismicColorMap from './seismic-colormap.json';
```

**Comment by Brynjulf** [comment]
you could also keep it as a one-liner:
```javascript
export { default as seismicColorMap } from './seismic-colormap.json';
```

**Comment by ooystein** [comment]
Fixed import!

Confirmed that highlight.js is bumped to a dependabot-"approved" version .

**Review by Brynjulf — APPROVED** [review]
LGTM

**Pull request merged**
