### PR TITLE
initial drawing for the api

### PR DESCRIPTION
**Pull request by Brynjulf**

### CODE REVIEW

**Comment by andreabrambilla** [comment]
I was thinking, can we try to write a snippet of code about how people would use the Intersection component? Possibly differentiating between the high level API (which also compute the intersection) and the low level API (which assumes pre-transformed data is passed in).

At the low level (LL) I'd expect users to pass in wellpath, surfaces, seismic, etc, as already transformed 2D layers, in a coordinate system that is already aligned. If it turns out to be necessary (see #128 ) the transformation has to be passed in as well. Casing and completions are likely specified in terms of MD and diameter. I guess the ZoomAndPan handler should be available also when the LL API is used

At the High Level (HL) instead I'd expect users will pass in data in 3D, such as the position log (in the coordinate system you described) and stratigraphic surfaces in some appropriate 3D format. 

Are my considerations correct, or am I completely off? If we agree on what I wrote above, I wonder to what API level the _Layer_ convept should belong to

**Comment by Brynjulf** [comment]
@andreabrambilla, i think that we should supply code snippets of the high level and low level examples in storybook

**Comment by andreabrambilla** [comment]
I have looked at the diagrams, great job :+1:
Maybe having all the methods in the diagram is a bit overkill, but all in all manageable.

I do have some notes/comments/question, please let me know if any of this is wrong:
1. I though that the axes and the overlay were just Layers, why do they get their own box in the `intersection-architecture` drawing?
2. When using the Intersection, there is always 1 instance of the controller, 1 of the layer manager, 1 zoom pan handler, 1 reference system, and several layers.
3. The user has to explicitly instantiate only the `Controller` and the `Layers`, he/she does not need to interact with any of the other classes, right?
4. I know the reference system is not part of this PR, but I need to touch on that to get to point 5. further down:
  - For the Controller, a reference system can be passed as input. If not, the reference system is automatically computed from the well path that is passed in. 
  - The main responsibility of the reference system is to convert points (and vectors?) from the 3D space to the _curtain_ (and vice-versa). And also from points in MD to the curtain (and possibly vice-versa). Is that correct?
  - The ZoomPanHandler takes care of defining the viewport on the curtain
5. I still struggle to define in a concise way what is the role of the `Layer` object are. There is this abstract input field called `data`, I assume that data has to be either in the 3D space or the MD space. The I guess each layer receives/reads the viewport from the ZoomPanHandler. The reference system is clearly necessary to map the viewport to the data. If what I wrote so far is correct, then the main responsibility of a Layer is to produce a 2D picture. And Ideally that 2D picture should be a rendering of the input data projected on the curtain, within the boundaries of the viewport. Does this make sense?

**Comment by Brynjulf** [comment]
@andreabrambilla ,

1. Both the axis and the overlay have different behaviour from a layer. Technically they are separate elements that overlay on top of the other layers. 
2. The controller is the main interface for the intersection component, the layer manager and zoom and pan handler are created when the controller is created. The layers can either be added when creating the controller or as you go. and the reference system is created if you pass in either a path or an instance of the reference system, either upon creation or after the controller has been created.
3. That is correct, although axis is dependent on options being passed into the controller upon creation, the rest are created regardless.
4.
* That is correct. If both are supplied, the input reference system takes priority over the input path.
* The main responsibility of the reference system would be to keep track of the path with its trajectory and curtain projection, and be able to get coordinates or a length along those
* Yes
5. What the data field consists of depends on the layer. For most of our layers the data input is dependent on either coordinates or md, but that is up to the implemented layer itself. The zoom and pan handler does keep track of the viewport, and feed all the information to the various layers. A layer is a container with various methods and properties to draw something, usually with the help of the reference system to place the data according to the curve.

**Comment by andreabrambilla** [comment]
So, a layer is just a class that renders some data. The only actual requirements it to inherit from `Layer` and re-implement some of the methods.

I still have some doubts about the reference system, I guess we should try to improve the documentation a bit. And maybe we should create a _Glossary_ page in the documentation, so that we avoid using ambiguous terms (eg, what's the difference between trajectory, curve, path? What's the difference between curtain space, screen space, and displacement?). But that of course belongs to a different PR. This one can be merged :+1:

**Comment by Brynjulf** [comment]
i agree, a glossary should help a lot

**Pull request merged**
