### PR TITLE
feat: destroy method on Controller

### PR DESCRIPTION
**Pull request by ooystein**
- fix bug in PixiLayer onUnmount
- change class name in createLayerContainer, class name was also used in LayerManager
- implement destroy method on Controller to remove overlay and layers from DOM, unmount layers and unset references

Destroy is implemented to help applications safely clean up after use.

### CODE REVIEW

**Review by Brynjulf — APPROVED** [review]
LGTM

**Comment by Brynjulf** [comment]
what bug is caused by not destructuring renderType?

**Comment by ooystein** [comment]
`renderType` is a getter and was called after Pixi Application and Renderer was destroyed with `this.ctx.destroy()` causing `this.ctx.renderer` to be undefined.

``` Typescript
get renderType(): RENDERER_TYPE {
  return this.ctx.renderer.type;
}
````

Maybe making renderType a method insted of a getter would have been better for clarity.

**Comment by Brynjulf** [comment]
In that case I would want a comment on the importance of having the value of the renderType before it is destroyed, because then it's not a case of syntactic sugar.

**Comment by ooystein** [comment]
Good point. Added comment and changed to method!

**Pull request merged**
