### PR TITLE
chore: update d3 to ^3

### PR DESCRIPTION
**Pull request by ooystein**
- Update to d3 ^3.
- Switch from d3.mouse to d3.pointer
- Remove use of d3.event and use event passed in on callback
- Fix some typing issues with use of d3
- Remove ts-jest
- Setup babel for use with jest
- Run tsc for type checking together with tests

### CODE REVIEW

**Comment by ooystein** [comment]
This is a bigger update to d3 and might require an update to applications using the library.

Do you have any thoughts on this update? @Brynjulf @HavardNJ 

We are in the process of updating d3 in our application and libraries, but can give it some time before we merge this in if it will create problems for anyone else.

**Comment by ooystein** [comment]
Tests are currently failing. Have to fix jest setup to work with ES Modules

**Review by Brynjulf — COMMENTED** [review]
My immediate thought is that this would add on the import cost for projects not using d3 for anything other than this component, but that would be unrealistic for most projects (including our own). So I'm for the change, I also see that we have to do some cleanup in our own project with regards to using sub-packages (ex. d3-selection) vs just using the main behemoth (d3). 

From what I could see d3.mouse is to be replaced with d3.pointer from v6 and above, in our project we are currently on v5.16.0 so we would want to get that up, but i don't think we have anything new we want to introduce in this package so there should not be anything stopping this pull request from being published from what I can see

**Comment by ooystein** [comment]
We can keep using the packages directly, I switched to using `d3` mainly to simplify the imports. The upgrades to latest version is what we are after. 

I would expect most applications to use three shaking during build to remove unused parts of the package but maybe that's bad sport from a library to "demand".

**Comment by ooystein** [comment]
ts-jest seems to have issues working correctly with ES module dependencies. Switched to using standard jest babel setup and doing the type checking separately with tsc.

PR is now complete and ready.

**Comment by ovineq** [comment]
Hey there,
I work on the same team as @ooystein. Is there anything we can help with to resolve this PR?

We see that you have another opened PR in https://github.com/equinor/esv-intersection/pull/463 for some optimization improvements. We're fine with merging that one first, if that's desirable.

**Review by ovineq — APPROVED** [review]

**Pull request merged**
