### PR TITLE
Example of transformation of geomodel layer data from POZO

### PR DESCRIPTION
**Pull request by HavardNJ**

### CODE REVIEW

**Comment by HavardNJ** [comment]
@andreabrambilla Shows code for transforming POZO data to low level format used for surfaces in intersection

**Comment by andreabrambilla** [comment]
I was expecting it to be much worse, this looks pretty straightforward. Should we consider adding also a wellbore path here? Just to see how painful it will be to make sure things are aligned. Or shall we leave that to a separate issue?

**Comment by HavardNJ** [comment]
If we could get a wellbore path in whatever format they are using we could add that as well, I think that would be useful.

**Comment by andreabrambilla** [comment]
I wrote them a couple of days ago, waiting for an answer

**Comment by nilsml** [comment]
This PR has been laying here forever. Should we just close it @HavardNJ?

**Comment by HavardNJ** [comment]
Yes, I don't think there is need for it.

**Pull request closed without merging**
